# Generated by Django 5.0.8 on 2024-10-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='address',
            field=models.CharField(default='Address', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='contact_name',
            field=models.CharField(default='Jesteena', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='contact_number',
            field=models.CharField(default='+91 9633867121', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Technicians.department'),
        ),
        migrations.AddField(
            model_name='technician',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Technicians.designation'),
        ),
    ]
