# Generated by Django 5.0.8 on 2024-10-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0002_technician_address_technician_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-date_added',), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ('-date_added',), 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'ordering': ('-date_added',), 'verbose_name': 'Technician', 'verbose_name_plural': 'Technicians'},
        ),
    ]
