# Generated by Django 5.0.8 on 2024-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0003_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='relation',
            field=models.CharField(default='Husband', max_length=50),
            preserve_default=False,
        ),
    ]
