# Generated by Django 5.0.8 on 2024-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0004_technician_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='status',
            field=models.CharField(default='ON SERVICE', max_length=25),
        ),
    ]
