# Generated by Django 5.0.8 on 2024-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0005_technician_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
