# Generated by Django 4.2.7 on 2024-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0006_alter_technician_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
