# Generated by Django 5.1.4 on 2024-12-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0007_department_info_designation_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Technicians.department'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='designation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Technicians.designation'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
