# Generated by Django 5.0.8 on 2024-10-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_technicians',
            new_name='is_technician',
        ),
    ]
