# Generated by Django 5.0.8 on 2024-10-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_phone_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
    ]
