# Generated by Django 5.1.4 on 2025-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-name',), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
