# Generated by Django 5.0.8 on 2024-10-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
