# Generated by Django 5.1.4 on 2025-01-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='technician',
            new_name='staff',
        ),
    ]
