# Generated by Django 5.1.4 on 2025-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_technician_expense_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ('-name',), 'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
    ]
