# Generated by Django 5.0.8 on 2024-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], default='INCOME', max_length=50),
            preserve_default=False,
        ),
    ]
