# Generated by Django 5.1.4 on 2025-01-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_transactioncategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ('name',), 'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
    ]
