# Generated by Django 4.2.16 on 2024-12-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('PETTY', 'PETTY'), ('SELF', 'SELF'), ('CREDIT', 'CREDIT')], max_length=50),
        ),
    ]
