# Generated by Django 5.1.4 on 2025-01-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_transaction_customer_transaction_lead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
