# Generated by Django 4.2.20 on 2025-04-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0011_remove_oncall_is_update_allowed_and_more'),
        ('Accounts', '0008_alter_bankaccount_auto_id_alter_transaction_auto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='on_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Works.oncall'),
        ),
    ]
