# Generated by Django 5.2.7 on 2025-10-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_transaction_account_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='work',
        ),
    ]
