# Generated by Django 5.2.7 on 2025-10-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wage',
            name='updated',
            field=models.DateField(),
        ),
    ]
