# Generated by Django 5.2.7 on 2025-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_alter_wage_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ('-type', 'name'), 'verbose_name': 'Transaction Category', 'verbose_name_plural': 'Transaction Categories'},
        ),
    ]
