# Generated by Django 5.2.7 on 2025-10-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_alter_transaction_options_and_more'),
        ('Works', '0023_alter_attendance_options_alter_oncall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Works.attendance'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('failed', 'FAILED'), ('approved', 'APPROVED'), ('payed', 'PAYED')], default='completed', max_length=50),
        ),
    ]
