# Generated by Django 5.2.7 on 2025-10-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_transaction_attendance_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('failed', 'FAILED'), ('approved', 'APPROVED'), ('paid', 'PAID')], default='completed', max_length=50),
        ),
    ]
