# Generated by Django 4.2.20 on 2025-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0003_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
