# Generated by Django 4.2.20 on 2025-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0004_alter_department_auto_id_alter_designation_auto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_wage',
            field=models.FloatField(default=0.0),
        ),
    ]
