# Generated by Django 5.2.1 on 2025-05-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0005_staff_staff_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Workforce.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Workforce.designation'),
            preserve_default=False,
        ),
    ]
