# Generated by Django 5.2.7 on 2025-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0007_alter_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='aadhar',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
