# Generated by Django 5.1.4 on 2025-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-name',), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
