# Generated by Django 5.0.8 on 2024-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
