# Generated by Django 5.1.4 on 2025-01-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
