# Generated by Django 5.1.4 on 2025-01-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
