# Generated by Django 4.2.7 on 2024-12-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_alter_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('individual', 'individual'), ('industrial', 'industrial')], max_length=50),
        ),
    ]
