# Generated by Django 5.2.1 on 2025-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_customer_auto_id_alter_followup_auto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise')], max_length=50),
        ),
    ]
