# Generated by Django 4.2.7 on 2024-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('individual', 'individual'), ('enterprice', 'enterprice')], max_length=50),
        ),
    ]
