# Generated by Django 5.2.7 on 2025-10-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_transaction_lead_remove_transaction_work'),
        ('Customers', '0009_remove_customer_active_customer_status_and_more'),
        ('Works', '0018_remove_requisitionitem_requisition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='staffs',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updater',
        ),
        migrations.DeleteModel(
            name='Followup',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
