# Generated by Django 4.2.7 on 2024-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Technicians', '0007_department_info_designation_info'),
        ('Customers', '0011_alter_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='staffs',
            field=models.ManyToManyField(to='Technicians.technician'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONVERTED', 'CONVERTED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
