# Generated by Django 4.2.16 on 2024-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0012_lead_staffs_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='additional_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='scope_of_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='site_condetion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
