# Generated by Django 4.2.16 on 2024-12-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0013_lead_additional_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_update_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
