# Generated by Django 5.1.4 on 2025-01-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='technicians',
            new_name='staffs',
        ),
    ]
