# Generated by Django 5.1.4 on 2025-01-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0002_rename_technicians_work_staffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='technician',
            new_name='staff',
        ),
    ]
