# Generated by Django 5.1.4 on 2025-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0003_alter_department_options_alter_designation_options_and_more'),
        ('Works', '0003_rename_technician_attendance_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='staffs',
        ),
        migrations.AddField(
            model_name='work',
            name='technicians',
            field=models.ManyToManyField(to='Workforce.staff'),
        ),
    ]
