# Generated by Django 5.1.4 on 2025-01-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0004_remove_work_staffs_work_technicians'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='technicians',
            new_name='staffs',
        ),
    ]
