# Generated by Django 4.2.20 on 2025-04-29 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Services', '0004_alter_category_options_alter_service_options'),
        ('Workforce', '0003_alter_department_options_alter_designation_options_and_more'),
        ('Customers', '0007_remove_customer_status_customer_active'),
        ('Works', '0005_rename_technicians_work_staffs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('auto_id', models.PositiveIntegerField(db_index=True, editable=False, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONVERTED', 'CONVERTED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('is_update_allowed', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('individual', 'individual'), ('enterprise', 'enterprise')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Services.category')),
                ('creator', models.ForeignKey(blank=True, editable=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_%(app_label)s_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Services.service')),
                ('staffs', models.ManyToManyField(to='Workforce.staff')),
                ('updater', models.ForeignKey(blank=True, editable=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater_%(app_label)s_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On Call',
                'verbose_name_plural': 'On Calls',
                'ordering': ('-date_added',),
            },
        ),
    ]
