# Generated by Django 5.1.4 on 2024-12-19 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0006_requisitionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitionitem',
            options={'ordering': ('-date_added',), 'verbose_name': 'RequisitionItem', 'verbose_name_plural': 'RequisitionItems'},
        ),
        migrations.AlterField(
            model_name='requisition',
            name='prepared',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
