# Generated by Django 4.2.20 on 2025-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0006_oncall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncall',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
