# Generated by Django 4.2.16 on 2024-12-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0014_lead_is_update_allowed'),
        ('Works', '0007_alter_requisitionitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customers.lead'),
        ),
    ]
