# Generated by Django 4.2.20 on 2025-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0007_alter_oncall_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='oncall',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='auto_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
