# Generated by Django 4.2.16 on 2024-12-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0008_alter_work_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='lead',
        ),
        migrations.AddField(
            model_name='requisition',
            name='work',
            field=models.ForeignKey(default='1c6eeadb-6136-4e1a-bff2-b2d42fe6c31d', on_delete=django.db.models.deletion.CASCADE, to='Works.work'),
            preserve_default=False,
        ),
    ]
