# Generated by Django 4.2.16 on 2024-12-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0009_remove_requisition_lead_requisition_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20),
        ),
    ]
