# Generated by Django 4.2.20 on 2025-04-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0009_oncall_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncall',
            name='email',
        ),
        migrations.RemoveField(
            model_name='oncall',
            name='location',
        ),
        migrations.RemoveField(
            model_name='oncall',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='oncall',
            name='name',
        ),
    ]
