# Generated by Django 4.2.20 on 2025-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0010_remove_oncall_email_remove_oncall_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncall',
            name='is_update_allowed',
        ),
        migrations.AddField(
            model_name='oncall',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='oncall',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oncall',
            name='site_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
