# Generated by Django 4.2.20 on 2025-04-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0011_remove_oncall_is_update_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='on_call',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Works.oncall'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Works.work'),
        ),
    ]
