# Generated by Django 5.2.1 on 2025-05-18 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_remove_customer_active_customer_status_and_more'),
        ('Works', '0013_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncall',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oncall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='oncall',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('enterprise', 'Enterprise')], max_length=50),
        ),
    ]
