# Generated by Django 5.2.1 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workforce', '0007_alter_staff_status'),
        ('Works', '0014_alter_oncall_customer_alter_oncall_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='staffs',
            field=models.ManyToManyField(blank=True, to='Workforce.staff'),
        ),
    ]
