# Generated by Django 5.2.1 on 2025-05-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_remove_customer_active_customer_status_and_more'),
        ('Works', '0016_alter_oncall_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncall',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Customers.customer'),
        ),
    ]
