# Generated by Django 5.2.7 on 2025-10-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_transaction_lead_remove_transaction_work'),
        ('Works', '0017_alter_oncall_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitionitem',
            name='requisition',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='work',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='work',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='work',
            name='staffs',
        ),
        migrations.RemoveField(
            model_name='work',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='work',
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
        migrations.DeleteModel(
            name='RequisitionItem',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
