# Generated by Django 5.2.7 on 2025-10-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0018_remove_requisitionitem_requisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='wage',
            field=models.FloatField(default=0.0),
        ),
    ]
