# Generated by Django 5.2.7 on 2025-10-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0021_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
