# Generated by Django 5.2.7 on 2025-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0022_remove_task_status_task_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('-date',), 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='oncall',
            options={'ordering': ('-date',), 'verbose_name': 'On Call', 'verbose_name_plural': 'On Calls'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day'), ('QUARTER', 'Quarter Day')], default='FULL', max_length=20),
        ),
    ]
