# Generated by Django 5.2.7 on 2025-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0023_alter_attendance_options_alter_oncall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='wage_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=20),
        ),
    ]
