# Generated by Django 5.2.7 on 2025-10-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0024_attendance_wage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='wage_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=20),
        ),
    ]
