# Generated by Django 5.2.7 on 2025-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0024_attendance_wage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half'), ('quarter', 'Quarter')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='wage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
