# Generated by Django 5.2.7 on 2025-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Works', '0025_alter_attendance_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
